### ISSUE TITLE
Flush to disk

### ISSUE THREAD

**Issue by i3jjnc68emm** [Squalr/Squalr#245] opened 2018-02-17 10:21 UTC
I've tried scanning for a value in AC Origins (memory usage 7GB) and Squalr memory usage was after the scan at 9GB so it looks like it only copied the whole AC origins memory without flushing it to disk.

I think it should flush them to disk and only load them if necessary.

**Comment by zcanann** [comment] 2018-02-18 04:41
Duplicate of https://github.com/Squalr/Squalr/issues/7

**Closed by zcanann** 2018-02-18 04:41 UTC
